export const ApplicationStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  INSPECTION_PENDING: 'INSPECTION_PENDING',
  QUERY_RAISED: 'QUERY_RAISED',
  RESUBMISSION_REQUIRED: 'RESUBMISSION_REQUIRED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const;

export const DepartmentStatus = {
  PENDING: 'PENDING',
  IN_REVIEW: 'IN_REVIEW',
  QUERY: 'QUERY',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const;

export const DocumentStatus = {
  REQUIRED: 'REQUIRED',
  UPLOADED: 'UPLOADED',
  UNDER_VALIDATION: 'UNDER_VALIDATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
} as const;

export const InspectionStatus = {
  SCHEDULED: 'SCHEDULED',
  ASSIGNED: 'ASSIGNED',
  COMPLETED: 'COMPLETED',
  PASSED: 'PASSED',
  REINSPECTION_REQUIRED: 'REINSPECTION_REQUIRED'
} as const;

export const QueryStatus = {
  OPEN: 'OPEN',
  RESPONDED: 'RESPONDED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED'
} as const;

export const RenewalStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
  RENEWAL_SUBMITTED: 'RENEWAL_SUBMITTED',
  RENEWED: 'RENEWED'
} as const;
